@file:Suppress("DEPRECATION") // SchemaScopeInfo and withScopedSchemas are deprecated; BasicViaductFactory is a transitional API

package viaduct.service

import viaduct.apiannotations.StableApi
import viaduct.service.api.Viaduct
import viaduct.service.api.spi.NaiveTenantModuleBootstrapper
import viaduct.service.api.spi.TenantModuleBootstrapper

/**
 * A simpler factory for creating [Viaduct] instances with sensible defaults.
 *
 * Use this when you do not need fine-grained control over SPI implementations such as
 * error reporting, metrics, or exception handling. For full control, use [ViaductBuilder].
 *
 * @see ViaductBuilder
 */
@StableApi
object BasicViaductFactory {
    /**
     * A simple factory-function for [Viaduct] instances.
     *
     * Discovers tenant modules from resources files generated by the viaduct-module plugin at build time.
     *
     * @param tenantModuleBootstrapper bootstrapper used for tenant modules discovered from the
     *        classpath. Defaults to [NaiveTenantModuleBootstrapper].
     * @param scopedSchemas scoped schema definitions to register. Defaults to none (only the
     *        full schema is available).
     */
    @JvmOverloads
    fun create(
        tenantModuleBootstrapper: TenantModuleBootstrapper = NaiveTenantModuleBootstrapper,
        scopedSchemas: List<SchemaScopeInfo> = emptyList(),
    ): Viaduct =
        ViaductBuilder()
            .withTenantModuleBootstrapper(tenantModuleBootstrapper)
            .withScopedSchemas(scopedSchemas)
            .build()
}
